# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            meanSoup
tagline:          'A code'
description:      'I'm meansoup, </br> a software engineer.
url:              https://meansoup.github.io

author:
  name:           'meansoup'
  url:            https://meansoup.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://meansoup.github.io
