<VerseLabel>:
    height: content.texture_size[1]
    size_hint: 1, None
    halign: 'center'
    
    Label:
        id: verse
        text_size: self.width, None
        size_hint: .1, None
        height: content.texture_size[1]

    Label:
        id: content
        text_size: self.width, None
        height: self.texture_size[1]
        markup: True

<VerseTitle>:
    text_size: self.width, None
    height: self.texture_size[1]
    color: .341176, .807843, .980392, 1
    halign: 'center'